export const langSelect = (lang) => {
  switch (lang) {
    case "ar":
      return "ar-kw";
    case "en":
      return "en-gb";
    case "fr":
      return "fr";
    case "es":
      return "es";
    case "zh":
      return "zh-cn";
    default:
      break;
  }
};
export const langDisplay = (lang) => {
  switch (lang) {
    case "en":
      const vuk = {
        temperature: "Temperature",
        pressure: "Pressure",
        rain: "Rain & Snow",
        Rain:"Rain",
        wind: "Wind",
        visibility: "Visibility",
        humidity: "Humidity",
        uvindex: "Uv index",
        usindex: "US index",
        ukindex: "UK index",
        cloud: "Cloud",
        sun: "Sun ",
        moon: "Moon ",
        km: "Km/h",
        mm: "mm",
        mbar: "Mbar",
        feels: "feels",
        byhour: "By Hour",
        nextdays: "Next days",
        today: "Today",
        current: "Current",
        airquality: "Air Qualité",
        confirmation: "Confirmation",
        Alert: "Alert",
        placeHolder: "Enter your city here",
        english: "English",
        arabic: "Arabic",
        chinese: "Chinese",
        french: "French",
        spanish: "Spanish",
        close:"Close",
        usStatus: {
          Good: "Good",
          Moderate: "Moderate",
          Unhealthyforsensitivegroup: " Unhealthy for sensitive group",
          Unhealthy: "Unhealthy",
          VeryUnhealthy: "Very Unhealthy",
          Hazardous: "Hazardous",
        },
        ukStatus: {
          Low: "Low",
          Moderate: "Moderate",
          High: "High",
          VeryHigh: "Very High",
        },
        humStat: {
          veryhighHum: "Very High Humidity",
          highHum: "High Humidity",
          mediumHum: "Medium Humidity",
          lowHum: "Low Humidity",
        },
        visiStat: {
          veryBad: "Very Bad",
          bad: "Bad",
          average: "Average",
          good: "Good",
        },
        windStat: {
          quiet: "Quiet",
          verylightbreeze: "Very light breeze",
          lightbreeze: "Light breeze",
          littlebreeze: "Little breeze",
          moderatebreeze: "Moderate breeze",
          goodbreeze: "Good breeze",
          freshwind: "Fresh wind",
          gale: "Gale",
          gustofwind: "gust of wind",
          stronggale: "Strong gale",
          storm: "storm",
          violentstorm: "violent storm",
          hurricane: "hurricane",
        },
      };
      return vuk;

    case "fr":
      const vf = {
        temperature: "Température",
        pressure: "Pression",
        rain: "Pluie & Neige",
        Rain:"Pluie",
        wind: "Vent",
        visibility: "Visibilité",
        humidity: "Humidité",
        uvindex: "index UV",
        usindex: "index US",
        ukindex: "index UK",
        cloud: "Nuages",
        sun: "Soleil ",
        moon: "Lune ",
        km: "Km/h",
        mm: "mm",
        mbar: "Mbar",
        feels: "Ressenti",
        byhour: "Par Heure",
        nextdays: "Prochain Jours",
        today: "Aujourd'hui",
        current: "Maintenant",
        airquality: "Qualité de l'aire",
        confirmation: "Confirmation",
        Alert: "Alert",
        placeHolder: "Entrez votre ville ici",
        english: "Anglais",
        arabic: "Arabe",
        chinese: "Chinois",
        french: "Français",
        spanish: "Espagnol",
        close:"Fermer",
        usStatus: {
          Good: "Bon",
          Moderate: "Modérée",
          Unhealthyforsensitivegroup: "Malsain pour le groupe sensible",
          Unhealthy: "Malsain",
          VeryUnhealthy: "Très malsain",
          Hazardous: "Dangereux",
        },
        ukStatus: {
          Low: "Faible",
          Moderate: "Modérée",
          High: "Élevé",
          VeryHigh: "Très élevé",
        },
        humStat: {
          veryhighHum: "Trés Forte Humidité",
          highHum: "Forte Humidité",
          mediumHum: "Humidité moyenne",
          lowHum: "Faible humidité",
        },
        visiStat: {
          veryBad: "Très Mauvaise",
          bad: "Mauvaise",
          average: "Moyenne",
          good: "Bonne",
        },
        windStat: {
          quiet: "Calme",
          verylightbreeze: "Très légère brise",
          lightbreeze: "Légère brise",
          littlebreeze: "Petite brise",
          moderatebreeze: "Jolie brise",
          goodbreeze: "Bonne brise",
          freshwind: "Vent frais",
          gale: "Grand frais",
          gustofwind: "Coup de vent",
          stronggale: "Fort coup de vent",
          storm: "Tempête",
          violentstorm: "Violente tempête",
          hurricane: "Ouragan",
        },
      };
      return vf;

    case "ar":
      const va = {
        temperature: "درجة الحرارة",
        pressure: "ضغط",
        rain: "المطر والثلوج",
        Rain:"المطر",
        wind: "الرياح",
        visibility: "الرؤية",
        humidity: "الرطوبة",
        uvindex: "مؤشر UV",
        usindex: "مؤشر US",
        ukindex: "مؤشر UK",
        cloud: "الغيوم",
        sun: "شمس",
        moon: "قمر",
        km: "س/كم",
        mm: "مم",
        mbar: "ميليبار",
        feels: "درجة المحسوسة",
        byhour: "كل ساعة",
        nextdays: "الأيام القادمة",
        today: "اليوم",
        current: "الآن",
        airquality: "جودة الهواء",
        confirmation: "تأكيد",
        Alert: "التنبيه",
        placeHolder: "أدخل مدينتك هنا",
        english: "إنجليزي",
        arabic: "عربية",
        chinese: "صيني",
        french: "فرنسي",
        spanish: "إسباني",
        close:"غلق",
        usStatus: {
          Good: "جيد",
          Moderate: "معتدل",
          Unhealthyforsensitivegroup: "غير صحي للمجموعة الحساسة",
          Unhealthy: "غير صحي",
          VeryUnhealthy: "غير صحي للغاية",
          Hazardous: "خطيرة",
        },
        ukStatus: {
          Low: "منخفض",
          Moderate: "معتدل",
          High: "مستوى عالي",
          VeryHigh: "عالي جدا",
        },
        humStat: {
          veryhighHum: "رطوبة عالية جد",
          highHum: "رطوبة عالية",
          mediumHum: "رطوبة متوسطة",
          lowHum: "انخفاض الرطوبة",
        },
        visiStat: {
          veryBad: "سيئ جدا",
          bad: "سيئ",
          average: "المتوسط",
          good: "جيد",
        },
        windStat: {
          quiet: "هادئ",
          verylightbreeze: "نسيم خفيف جدا",
          lightbreeze: "نسيم خفيف ",
          littlebreeze: "نسيم",
          moderatebreeze: "نسيم جميل",
          goodbreeze: "نسيم جيد",
          freshwind: "رياح باردة",
          gale: "رياح باردة جد",
          gustofwind: "رياح قوية",
          stronggale: "رياح قوية جد",
          storm: "عاصفة",
          violentstorm: "عاصفة شديدة",
          hurricane: "إعصار",
        },
      };

      return va;
    case "es":
      const ve = {
        temperature: "temperatura",
        pressure: "presión",
        rain: "lluvia y nieve",
        Rain:"lluvia",
        wind: "viento",
        visibility: "visibilidad",
        humidity: "humedad",
        uvindex: "índice UV",
        usindex: "índice US",
        ukindex: "índice UK",
        cloud: "nubes",
        sun: "sol",
        moon: "luna ",
        km: "Km/h",
        mm: "mm",
        mbar: "Mbar",
        feels: "Sentido",
        byhour: "Por Hora",
        nextdays: "Próximos Días",
        today: "Hoy",
        current: "Ahora",
        airquality: "Calidad de la zona",
        confirmation: "confirmación",
        Alert: "Alert",
        placeHolder: "Entra en tu ciudad aquí",
        english: "inglés",
        arabic: "Arábica",
        chinese: "Chino",
        french: "francés",
        spanish: "español",
        close:"Cerrar",
        usStatus: {
          Good: "Bueno",
          Moderate: "Moderado",
          Unhealthyforsensitivegroup: "Poco saludable para el grupo sensible",
          Unhealthy: "Poco saludable",
          VeryUnhealthy: "Muy poco saludable",
          Hazardous: "Peligroso",
        },
        ukStatus: {
          Low: "Baja",
          Moderate: "Moderado",
          High: "Alto",
          VeryHigh: "Muy Alto",
        },
        humStat: {
          veryhighHum: "Muertos Fuerte Humedad",
          highHum: "Alta Humedad",
          mediumHum: "Humedad media",
          lowHum: "Baja humedad",
        },
        visiStat: {
          veryBad: "Muy Mala",
          bad: "Mala",
          average: "Promedio",
          good: "Mucama",
        },
        windStat: {
          quiet: "Tranquilo",
          verylightbreeze: "Brisa muy ligera",
          lightbreeze: "Ligera brisa",
          littlebreeze: "Brisa",
          moderatebreeze: "Bonita brisa",
          goodbreeze: "Buena brisa",
          freshwind: "Viento fresco",
          gale: "Muy fresco",
          gustofwind: "Viento",
          stronggale: "Fuerte soplo de viento",
          storm: "Tormenta",
          violentstorm: "Violenta tormenta",
          hurricane: "Huracán",
        },
      };
      return ve;
    case "zh":
      const vc = {
        temperature: "温度",
        pressure: "大气压力",
        rain: "雨和雪",
        Rain:"雨和雪",
        wind: "强风",
        visibility: "能见度",
        humidity: "湿度",
        uvindex: "UV 指数",
        usindex: "US 指数",
        ukindex: "UK 指数",
        cloud: "云层",
        sun: "太阳 ",
        moon: "月球 ",
        km: "时速",
        mm: "毫米",
        mbar: "毫巴",
        feels: "感觉到的温度",
        byhour: "按小时计算",
        nextdays: "下一个天数",
        today: "今天的情况",
        current: "现在,请",
        airquality: "该地区的质量",
        confirmation: "确认",
        Alert: "警报",
        placeHolder: "在这里进入您的城市",
        english: "英语",
        arabic: "阿拉伯",
        chinese: "中文",
        french: "法语",
        spanish: "西班牙语",
        close:"关闭",
        usStatus: {
          Good: "很好，很好",
          Moderate: "中等程度的",
          Unhealthyforsensitivegroup: "敏感群体不健康",
          Unhealthy: "不健康的人",
          VeryUnhealthy: "非常不健康",
          Hazardous: "危险",
        },
        ukStatus: {
          Low: "低",
          Moderate: "中等程度的",
          High: "高度（高）",
          VeryHigh: "非常High（高）",
        },
        humStat: {
          veryhighHum: "类天气",
          highHum: "高湿度",
          mediumHum: "中等湿度",
          lowHum: "低湿度",
        },
        visiStat: {
          veryBad: "非常糟糕",
          bad: "不善",
          average: "平均",
          good: "良好",
        },
        windStat: {
          quiet: "安静的环境",
          verylightbreeze: "很轻的微风",
          lightbreeze: "轻盈的微风",
          littlebreeze: "小风微风",
          moderatebreeze: "一阵清风",
          goodbreeze: "好风好风",
          freshwind: "清新的风",
          gale: "大手续费",
          gustofwind: "狂风部队",
          stronggale: "一阵强风",
          storm: "暴风雨（英文",
          violentstorm: "严重的暴风雨",
          hurricane: "飓风（飓风",
        },
      };
      return vc;
    default:
      break;
  }
};
